dataset: "tum"
device: "cuda:0"
method: "vigs"
# inputdir: # TODO: input dataset location
scene: "rgbd_dataset_freiburg1_desk"
outputdir: output/tum/desk
dataloader: "gradslam"
use_gt_depth: false # If False, a monocular depth estimator is used
dpt_model: "midas"
white_background: false
scene_radius_depth_ratio: 2
# iteration: 592
start_idx: 0
stride: 1
# early_stop_idx: 100
desired_height: 480
desired_width: 640
save_iterations:
  - 1
eval_every: 5
debug:
  get_runtime_stats: true
  create_video: true
  save_keyframes: false
pipeline:
  convert_SHs_python: false
  compute_cov3D_python: false
  transform_means_python: true
  force_isotropic: false
  use_rgb: false
tracking:
  iters: 100
  use_gt_pose: false
  dynamics_model: "const_velocity"
  use_imu_loss: false
  imu_T_weight: 0.0
  imu_q_weight: 0.0
  use_depth_estimate_loss: false
  pearson_weight: 0.05
  # learning rates
  position_lr: 0.001
  rotation_lr: 0.003
mapping:
  iters: 150
  kf_every: 5
  niqe_kf: true
  niqe_window_size: 5
  kf_window_size: 25
  covisibility_level: 1
  min_covisibility: 0.95
  kf_covisibility: 0.1
  do_BA: false
  use_depth_estimate_loss: true
  pearson_weight: 0.05
  # model params
  sh_degree: 0
  # learning rates
  cam_t_lr: 0.001
  cam_q_lr: 0.003
  position_lr_init: 0.0001
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.001
  rotation_lr: 0.001
  rgb_lr: 0.0025
  spatial_lr_scale: 1
  percent_dense: 0.01
  lambda_dssim: 0.2
  # TODO:　modify these
  min_opacity: 0.005
  densification_interval: 50
  pruning_interval: 50
  size_threshold: 100
  opacity_reset_interval: 500
  densify_from_iter: 0
  densify_until_iter: 50
  densify_grad_threshold: 0.0002
cam:
  image_height: 480
  image_width: 640
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  crop_edge: 8
  png_depth_scale: 5000.0
  fps: 30
